server:
  port: 8093

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          # AUTENTICACIÓN - RUTAS PÚBLICAS
            # LOGIN - Ruta pública
            - id: auth-login
              uri: http://localhost:8098  # URI del MS-Authentication
              predicates:
                - Path=/api/v1/gateway/auth/login
                - Method=POST
              filters:
                - RewritePath=/api/v1/gateway/auth/login, /api/auth/login

            # CREAR CLIENTE - Ruta pública
            - id: auth-create-client
              uri: http://localhost:8098
              predicates:
                - Path=/api/v1/gateway/auth/createclient
                - Method=POST
              filters:
                - RewritePath=/api/v1/gateway/auth/createclient, /api/auth/createclient

            # REFRESH TOKEN - Ruta pública
            - id: auth-refresh
              uri: http://localhost:8098
              predicates:
                - Path=/api/v1/gateway/auth/refresh
                - Method=POST
              filters:
                - RewritePath=/api/v1/gateway/auth/refresh, /api/auth/refresh

          # AUTENTICACIÓN - RUTAS PROTEGIDAS
            # CREAR ADMIN - Requiere permiso usuarios:crear_admin
            - id: auth-create-admin
              uri: http://localhost:8098
              predicates:
                - Path=/api/v1/gateway/auth/createadmin
                - Method=POST
              filters:
                - AuthorizationFilter=CreateAdmin
                - RewritePath=/api/v1/gateway/auth/createadmin, /api/auth/createadmin
          
          # INVENTARIO - RUTAS PUBLICAS
            # PRODUCTOS - LISTAR 
            - id: productos-listar-public
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/productos/listar
                - Method=GET
              filters:
                - RewritePath=/api/v1/gateway/productos/listar, /api/v1/productos/listar
            
            # PRODUCTOS - BUSCAR POR ID
            - id: productos-buscarID-public
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/productos/buscar/{id}
                - Method=GET
              filters:
                - RewritePath=/api/v1/gateway/productos/buscar/(?<id>.*), /api/v1/productos/buscar/${id}
            
            # PRODUCTOS - BUSCAR POR NOMBRE
            - id: productos-buscar-nombre-public
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/productos/buscarProductos/{nombre}
                - Method=GET
              filters:
                - RewritePath=/api/v1/gateway/productos/buscarProductos/(?<nombre>.*), /api/v1/productos/buscarProductos/${nombre}
          
          # INVENTARIO - RUTAS PROTEGIDAS
            # PRODUCTOS - CREAR PRODUCTO
            - id: productos-crear
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/productos/crear
                - Method=POST
              filters:
                - AuthorizationFilter=Inventario:Crud
                - RewritePath=/api/v1/gateway/productos/crear, /api/v1/productos/crear
            
            # PRODUCTOS - ACTUALIZAR PRODUCTO
            - id: productos-actualizar
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/productos/actualizar/{query}
                - Method=PUT,PATCH
              filters:
                - AuthorizationFilter=Inventario:Crud
                - RewritePath=/api/v1/gateway/productos/actualizar/(?<query>.*), /api/v1/productos/actualizar/${query}
            
            # CATEGORIAS - CREAR CATEGORIA
            - id: categorias-crear
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/gateway/categoria/nuevacategoria
                - Method=POST
              filters:
                - AuthorizationFilter=Inventario:Crud
                - RewritePath=/api/v1/gateway/categoria/nuevacategoria, /api/v1/categoria/nuevacategoria

            # CART - RUTAS PROTEGIDAS
              # CART - agregar producto al carrito
            - id: cart-agregar-producto
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/gateway/carts/agregarproducto
                - Method=POST
              filters:
                - AuthorizationFilter=Cart:Crud
                - RewritePath=/api/v1/gateway/carts/agregarproducto, /api/v1/carts/agregarproducto
                
            # CART - eliminar producto del carrito
            - id: cart-eliminar-producto
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/gateway/carts/eliminarproducto/{id}
                - Method=DELETE
              filters:
                - AuthorizationFilter=Cart:Crud
                - RewritePath=/api/v1/gateway/carts/eliminarproducto/(?<id>.*), /api/v1/carts/eliminarproducto/${id}
            # CART - ver carrito por ID de usuario
            - id: cart-ver-carrito
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/gateway/carts/vercarrito
                - Method=GET
              filters:
                - AuthorizationFilter=Cart:Crud
                - RewritePath=/api/v1/gateway/carts/vercarrito, /api/v1/carts/vercarrito
            # CART - vaciar carrito por ID de usuario
            - id: cart-vaciar-carrito
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/gateway/carts/vaciarcarrito
                - Method=DELETE
              filters:
                - AuthorizationFilter=Cart:Crud
                - RewritePath=/api/v1/gateway/carts/vaciarcarrito, /api/v1/carts/vaciarcarrito
            
            # CART ADMIN - ver todos los carritos (requiere permiso CartAdmin:Crud)
            - id: cart-ver-todos-carritos 
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/gateway/cartsadmin/all
                - Method=GET
              filters:
                - AuthorizationFilter=CartAdmin:Crud
                - RewritePath=/api/v1/gateway/cartsadmin/all, /api/v1/cartsadmin/all
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
jwt:
  secret-key: 4ba2e4c6c0eab7c2ed629fbdc76ac515a9a82d1d41ebfc483060ab8816544aa6
  expiration: 3600000
