server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/arka_db 
    username: postgres
    password: 123
    pool:
      initial-size: 5
      max-size: 20


logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG  # Ver queries SQL ejecutadas
    io.r2dbc.postgresql.PARAM: DEBUG  # Ver parámetros de las queries
    com.tuempresa.cart: DEBUG          # Ver logs de tu aplicación

ms:
  inventario:
    baseUri: "lb://MSInventario"
    uriPath: "/api/v1/productos/stockprice/{id}"
  cart:
    abandonCart:
      time: 1 # tiempo en minutos para considerar un carrito abandonado
    functionAbandonCart:
      time: 0.5 # tiempo en minutos para ejecutar la función de carrito abandonado