server:
  port: 8095
  
ms:
  inventarioBuscar:
    baseUri: "lb://MSInventario"
    uriPath: "/api/v1/productos/stockprice/{id}"
  inventarioActualizar:
    baseUri: "lb://MSInventario"
    uriPath: "/api/v1/productos/actualizar/{id}"
  auth:
    baseUri: "lb://MSAuthentication"
    uriPath: "/api/auth/consuluser/{id}"

spring:
  # --- Configuración de MongoDB Reactive ---
  data:
    mongodb:
      # Usa la DB que ya creaste o vas a usar
      uri: mongodb://localhost:27017/arka_db_mongo